name: Run KittenTTS FastAPI

on:
  workflow_dispatch:
  push:

jobs:
  serve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install wheel
          pip install fastapi uvicorn
          pip install kittentts  # or prebuilt .whl if you uploaded

      - name: Run FastAPI with Cloudflare tunnel
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 &
          sleep 10
          curl -fsSL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          nohup ./cloudflared tunnel --url http://localhost:8000 > tunnel.log 2>&1 &

          # wait for tunnel
          sleep 5
          URL=$(grep -o 'https://.*trycloudflare.com' tunnel.log | head -n1)

          echo "FastAPI running at $URL"

          # send to your n8n webhook
          curl -X POST "https://drn8n.up.railway.app/webhook/b24ea92e-9123-4cb1-8a79-9a08ae45c536" \
            -H "Content-Type: application/json" \
            -d "{\"url\": \"$URL\"}"

      - name: Keep Alive 20 minutes
        run: sleep 1200
